import { createSlice } from "@reduxjs/toolkit";

const initialState = [
  {
    id: 1,
    name: "casual shirt",
    status: "need to confirm",
    price: 150000,
    category: ["man", "casual"],
    size: [
      { id: 1, size: "M" },
      { id: 2, size: "L" },
      { id: 3, size: "XL" },
    ],
    color: [
      { id: 1, color: "#FFD89C" },
      { id: 2, color: "#9BCDD2" },
    ],
    stocks: 12,
    cover: "url_cover_photos",
    photos: ["url_photo"],
  },
  {
    id: 2,
    name: "women's casual shirt 1",
    status: "need to confirm",
    price: 120000,
    category: ["women", "casual"],
    size: [
      { id: 1, size: "M" },
      { id: 2, size: "L" },
      { id: 3, size: "XL" },
    ],
    color: [
      { id: 1, color: "#FFD89C" },
      { id: 2, color: "#9BCDD2" },
    ],
    stocks: 15,
    cover: "url_cover_photos_2",
    photos: ["url_photo_2"],
  },
  {
    id: 3,
    name: "Men's Casual Shirt 2",
    status: "need to confirm",
    price: 140000,
    category: ["men", "casual"],
    size: [
      { id: 1, size: "M" },
      { id: 2, size: "L" },
      { id: 3, size: "XL" },
    ],
    color: [
      { id: 1, color: "#FFD89C" },
      { id: 2, color: "#9BCDD2" },
    ],
    stocks: 8,
    cover: "url_cover_photos_3",
    photos: ["url_photo_3"],
  },
  {
    id: 4,
    name: "Women's Casual Shirt 2",
    status: "need to confirm",
    price: 90000,
    category: ["women", "casual"],
    size: [
      { id: 1, size: "M" },
      { id: 2, size: "L" },
      { id: 3, size: "XL" },
    ],
    color: [
      { id: 1, color: "#FFD89C" },
      { id: 2, color: "#9BCDD2" },
    ],
    stocks: 12,
    cover: "url_cover_photos_4",
    photos: ["url_photo_4"],
  },
  {
    id: 5,
    name: "Men's Casual Shirt 3",
    status: "need to confirm",
    price: 170000,
    category: ["men", "casual"],
    size: [
      { id: 1, size: "M" },
      { id: 2, size: "L" },
      { id: 3, size: "XL" },
    ],
    color: [
      { id: 1, color: "#FFD89C" },
      { id: 2, color: "#9BCDD2" },
    ],
    stocks: 10,
    cover: "url_cover_photos_5",
    photos: ["url_photo_5"],
  },
  {
    id: 6,
    name: "Women's Casual Shirt 3",
    status: "need to confirm",
    price: 80000,
    category: ["women", "casual"],
    size: [
      { id: 1, size: "M" },
      { id: 2, size: "L" },
      { id: 3, size: "XL" },
    ],
    color: [
      { id: 1, color: "#FFD89C" },
      { id: 2, color: "#9BCDD2" },
    ],
    stocks: 15,
    cover: "url_cover_photos_6",
    photos: ["url_photo_6"],
  },
  {
    id: 7,
    name: "Men's Casual Shirt 4",
    status: "need to confirm",
    price: 190000,
    category: ["men", "casual"],
    size: [
      { id: 1, size: "M" },
      { id: 2, size: "L" },
      { id: 3, size: "XL" },
    ],
    color: [
      { id: 1, color: "#FFD89C" },
      { id: 2, color: "#9BCDD2" },
    ],
    stocks: 8,
    cover: "url_cover_photos_7",
    photos: ["url_photo_7"],
  },
  {
    id: 8,
    name: "Women's Casual Shirt 4",
    status: "need to confirm",
    price: 95000,
    category: ["women", "casual"],
    size: [
      { id: 1, size: "M" },
      { id: 2, size: "L" },
      { id: 3, size: "XL" },
    ],
    color: [
      { id: 1, color: "#FFD89C" },
      { id: 2, color: "#9BCDD2" },
    ],
    stocks: 12,
    cover: "url_cover_photos_8",
    photos: ["url_photo_8"],
  },
  {
    id: 9,
    name: "Men's Casual Shirt 5",
    status: "need to confirm",
    price: 160000,
    category: ["men", "casual"],
    size: [
      { id: 1, size: "M" },
      { id: 2, size: "L" },
      { id: 3, size: "XL" },
    ],
    color: [
      { id: 1, color: "#FFD89C" },
      { id: 2, color: "#9BCDD2" },
    ],
    stocks: 10,
    cover: "url_cover_photos_9",
    photos: ["url_photo_9"],
  },
  {
    id: 10,
    name: "Women's Casual Shirt 5",
    status: "need to confirm",
    price: 100000,
    category: ["women", "casual"],
    size: [
      { id: 1, size: "M" },
      { id: 2, size: "L" },
      { id: 3, size: "XL" },
    ],
    color: [
      { id: 1, color: "#FFD89C" },
      { id: 2, color: "#9BCDD2" },
    ],
    stocks: 15,
    cover: "url_cover_photos_10",
    photos: ["url_photo_10"],
  },
  {
    id: 11,
    name: "Men's Casual Shirt 6",
    status: "need to confirm",
    price: 175000,
    category: ["men", "casual"],
    size: [
      { id: 1, size: "M" },
      { id: 2, size: "L" },
      { id: 3, size: "XL" },
    ],
    color: [
      { id: 1, color: "#FFD89C" },
      { id: 2, color: "#9BCDD2" },
    ],
    stocks: 8,
    cover: "url_cover_photos_11",
    photos: ["url_photo_11"],
  },
  {
    id: 12,
    name: "Women's Casual Shirt 6",
    status: "need to confirm",
    price: 85000,
    category: ["women", "casual"],
    size: [
      { id: 1, size: "M" },
      { id: 2, size: "L" },
      { id: 3, size: "XL" },
    ],
    color: [
      { id: 1, color: "#FFD89C" },
      { id: 2, color: "#9BCDD2" },
    ],
    stocks: 12,
    cover: "url_cover_photos_12",
    photos: ["url_photo_12"],
  },
  {
    id: 13,
    name: "Men's Casual Shirt 7",
    status: "need to confirm",
    price: 185000,
    category: ["men", "casual"],
    size: [
      { id: 1, size: "M" },
      { id: 2, size: "L" },
      { id: 3, size: "XL" },
    ],
    color: [
      { id: 1, color: "#FFD89C" },
      { id: 2, color: "#9BCDD2" },
    ],
    stocks: 10,
    cover: "url_cover_photos_13",
    photos: ["url_photo_13"],
  },
  {
    id: 14,
    name: "Women's Casual Shirt 7",
    status: "need to confirm",
    price: 110000,
    category: ["women", "casual"],
    size: [
      { id: 1, size: "M" },
      { id: 2, size: "L" },
      { id: 3, size: "XL" },
    ],
    color: [
      { id: 1, color: "#FFD89C" },
      { id: 2, color: "#9BCDD2" },
    ],
    stocks: 15,
    cover: "url_cover_photos_14",
    photos: ["url_photo_14"],
  },
  {
    id: 15,
    name: "Men's Casual Shirt 8",
    status: "need to confirm",
    price: 195000,
    category: ["men", "casual"],
    size: [
      { id: 1, size: "M" },
      { id: 2, size: "L" },
      { id: 3, size: "XL" },
    ],
    color: [
      { id: 1, color: "#FFD89C" },
      { id: 2, color: "#9BCDD2" },
    ],
    stocks: 8,
    cover: "url_cover_photos_15",
    photos: ["url_photo_15"],
  },
  {
    id: 16,
    name: "Women's Casual Shirt 8",
    status: "need to confirm",
    price: 90000,
    category: ["women", "casual"],
    size: [
      { id: 1, size: "M" },
      { id: 2, size: "L" },
      { id: 3, size: "XL" },
    ],
    color: [
      { id: 1, color: "#FFD89C" },
      { id: 2, color: "#9BCDD2" },
    ],
    stocks: 12,
    cover: "url_cover_photos_16",
    photos: ["url_photo_16"],
  },
  {
    id: 17,
    name: "Men's Casual Shirt 9",
    status: "need to confirm",
    price: 165000,
    category: ["men", "casual"],
    size: [
      { id: 1, size: "M" },
      { id: 2, size: "L" },
      { id: 3, size: "XL" },
    ],
    color: [
      { id: 1, color: "#FFD89C" },
      { id: 2, color: "#9BCDD2" },
    ],
    stocks: 10,
    cover: "url_cover_photos_17",
    photos: ["url_photo_17"],
  },
  {
    id: 18,
    name: "Women's Casual Shirt 9",
    status: "need to confirm",
    price: 95000,
    category: ["women", "casual"],
    size: [
      { id: 1, size: "M" },
      { id: 2, size: "L" },
      { id: 3, size: "XL" },
    ],
    color: [
      { id: 1, color: "#FFD89C" },
      { id: 2, color: "#9BCDD2" },
    ],
    stocks: 15,
    cover: "url_cover_photos_18",
    photos: ["url_photo_18"],
  },
  {
    id: 18,
    name: "Women's Casual Shirt 9",
    status: "need to confirm",
    price: 95000,
    category: ["women", "casual"],
    size: [
      { id: 1, size: "M" },
      { id: 2, size: "L" },
      { id: 3, size: "XL" },
    ],
    color: [
      { id: 1, color: "#FFD89C" },
      { id: 2, color: "#9BCDD2" },
    ],
    stocks: 15,
    cover: "url_cover_photos_18",
    photos: ["url_photo_18"],
  },
  {
    id: 20,
    name: "Women's Casual Shirt 10",
    status: "need to confirm",
    price: 100000,
    category: ["women", "casual"],
    size: [
      { id: 1, size: "M" },
      { id: 2, size: "L" },
      { id: 3, size: "XL" },
    ],
    color: [
      { id: 1, color: "#FFD89C" },
      { id: 2, color: "#9BCDD2" },
    ],
    stocks: 12,
    cover: "url_cover_photos_20",
    photos: ["url_photo_20"],
  },
  {
    id: 21,
    name: "Kids' Casual Shirt 1",
    status: "need to confirm",
    price: 90000,
    category: ["kids", "casual"],
    size: [
      { id: 1, size: "M" },
      { id: 2, size: "L" },
      { id: 3, size: "XL" },
    ],
    color: [
      { id: 1, color: "#FFD89C" },
      { id: 2, color: "#9BCDD2" },
    ],
    stocks: 8,
    cover: "url_cover_photos_4",
    photos: ["url_photo_4"],
  },
];

const productSlice = createSlice({
  name: "products",
  initialState,
  reducers: {},
});

export default productSlice.reducer;
